name: Build Bcrypt Ultimate

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Compile project and build jar (skip tests)
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bcrypt-ultimate-jar
          path: ./target/bcrypt-ultimate-1.0.0-jar-with-dependencies.jar
